### ISSUE TITLE
Straight-up fails to change region

### ISSUE THREAD

**Issue by Moire9** [Possum/LumaLocaleSwitcher#16]
Yeah. You heard. It straight up fails to change the region. This may, however, have to do with the fact I downloaded it from TitleDB. It does work in changing the game's language to one supported by the default region, but it cannot change it to out-of-region languages or actually change regions. So, yeah. Running Luma 8.1.1.

**Comment by Possum** [comment]
Can you comment on which game(s) it is having problems with?

Since the application is just a frontend to Luma's built-in region spoofing feature, it only changes what region and language the 3DS appears to the game. In other words, the game has to support it. It won't make, e.g., a USA region game become a EUR one, but instead it'll make the cart think it's running on a EUR system instead of a USA one. This has been useful for non-region locked games (such as Pokémon, in order to get region specific events) and is necessary for some games where Luma's region patching isn't enough (Bravely Default JPN version for instance).

**Comment by Moire9** [comment]
Oh. I see. I was testing it on MK7. You see, I region-changed my EmuNand to Europe so I could run my 3DS in German, and wanted to run MK7 in German too. My Gamecart-dumped copy was USA, so I ended up downloading a European version from FreeShop (it's not piracy if you own the game). I figured it would actually change the region of the game, and actually change it to out-of-region languages. I suppose I'll have to stick with German or English. I wanted to run it in Japanese. What _would_ be cool is if you got a copy of each region of the game, and merged the language files so you can change it to any language. Well, I see now. Thanks.
